ARG NET_IMAGE=6.0-bullseye-slim
FROM mcr.microsoft.com/dotnet/aspnet:${NET_IMAGE} AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:${NET_IMAGE} AS build
WORKDIR /src

# Copy necessary files and restore as distinct layer
COPY src/Simulation/Simulation.csproj ./src/Simulation/
RUN dotnet restore "src/Simulation/Simulation.csproj"

# Copy everything else and build
COPY . ./

WORKDIR "/src/src/Simulation/"
RUN dotnet build "Simulation.csproj" -c Release -o /app/build

# Build runtime image
FROM build AS publish
RUN dotnet publish --no-restore "Simulation.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=build /src/src/Simulation/install.sh ./install.sh

#
# Install dapr CLI
# RUN /bin/sh /app/install.sh

# Install daprd
ARG DAPR_BUILD_DIR
COPY $DAPR_BUILD_DIR /opt/dapr
ENV PATH="/opt/dapr/:${PATH}"
# RUN dapr init --slim
# Start
ENTRYPOINT ["dotnet", "Simulation.dll"]
