apiVersion: apps/v1
kind: Deployment
metadata:
  name: finecollectionservice
  namespace: dapr-trafficcontrol
  labels:
    app: finecollectionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finecollectionservice
  template:
    metadata:
      labels:
        app: finecollectionservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "finecollectionservice"
        dapr.io/app-port: "6001"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
        dapr.io/enable-api-logging: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/enable-profiling: "true"
    spec:
      containers:
      - name: finecollectionservice
        image: docker.liquid-capital.liquidcap.com:5000/finecollectionservice:1.0
        ports:
        - containerPort: 6001
        env:
          - name: USE_KUBERNETES_SECRETS
            value: "true"
          - name: SeqServerUrl
            value: "http://seq.dapr-trafficcontrol.svc.cluster.local"
      imagePullSecrets:
        - name: regcred

