apiVersion: v1
kind: Pod
metadata:
  name: network
  namespace: dapr-trafficcontrol
spec:
  containers:
  - name: network
    image: wbitt/network-multitool
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always