apiVersion: apps/v1
kind: Deployment
metadata:
  name: camerasimulation
  namespace: dapr-trafficcontrol
  labels:
    app: camerasimulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camerasimulation
  template:
    metadata:
      labels:
        app: camerasimulation
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "camerasimulation"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
        dapr.io/enable-api-logging: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/enable-profiling: "true"
    spec:
      containers:
      - name: camerasimulation
        image: docker.liquid-capital.liquidcap.com:5000/cameraimulation2:1.0
        env:
          - name: SeqServerUrl
            value: "http://seq.dapr-trafficcontrol.svc.cluster.local"
      imagePullSecrets:
        - name: regcred
