apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficcontrolservice
  namespace: dapr-trafficcontrol
  labels:
    app: trafficcontrolservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficcontrolservice
  template:
    metadata:
      labels:
        app: trafficcontrolservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "trafficcontrolservice"
        dapr.io/app-port: "6000"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
        dapr.io/enable-api-logging: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/enable-profiling: "true"
    spec:
      containers:
      - name: trafficcontrolservice
        image: docker.liquid-capital.liquidcap.com:5000/trafficcontrolservice:1.0
        ports:
        - containerPort: 6000
        env:
          - name: SeqServerUrl
            value: "http://seq.dapr-trafficcontrol.svc.cluster.local"
      imagePullSecrets:
        - name: regcred
