apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicleregistrationservice
  namespace: dapr-trafficcontrol
  labels:
    app: vehicleregistrationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicleregistrationservice
  template:
    metadata:
      labels:
        app: vehicleregistrationservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "vehicleregistrationservice"
        dapr.io/app-port: "6002"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
        dapr.io/enable-api-logging: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/enable-profiling: "true"
    spec:
      containers:
      - name: vehicleregistrationservice
        image: docker.liquid-capital.liquidcap.com:5000/vehicleregistrationservice:1.0
        ports:
        - containerPort: 6002
        env:
          - name: SeqServerUrl
            value: "http://seq.dapr-trafficcontrol.svc.cluster.local"
      imagePullSecrets:
        - name: regcred

