apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: exitcam
  namespace: dapr-trafficcontrol
spec:
# mqtt both supports input and output bindings
  type: bindings.mqtt
  version: v1
  metadata:
  - name: url
    value: mqtt://mosquitto:1883
  - name: topic
    value: trafficcontrol/exitcam
  - name: consumerID
    value: "{uuid}"
scopes:
  - trafficcontrolservice
  - cameraimulation